---

- name: Upgrade packages
  hosts: all
  become: yes

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

- name: Create users
  hosts: all
  become: yes

  tasks:
    - name: Create user deploy
      user:
        name: deploy
        shell: /bin/bash
        groups: sudo

- name: Install rbenv and dependencies
  hosts: all
  become: yes

  tasks:
    - name: Install rbenv
      apt:
        name: rbenv
        state: present
        update_cache: yes
    
    - name: Install dependencies
      apt: 
        name: "{{ item }}" 
        state: present 
        update_cache: yes
      with_items:
        - build-essential
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev

- name: Install git before rbenv configuration
  hosts: all
  become: yes

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

- name: Configure rbenv and install ruby
  hosts: all
  become: yes
  become_user: deploy

  tasks:
    - name: Automatically init rbenv
      lineinfile:
        dest: ~/.bashrc
        regexp: eval "\$\(rbenv init -\)"
        line: eval "$(rbenv init -)"
        insertafter: EOF

    - name: Install rbenv ruby-build plugin
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build
    
    - name: Automatically init ruby-build
      lineinfile:
        dest: ~/.bashrc
        regexp: export PATH="\$HOME\/.rbenv\/plugins\/ruby-build\/bin:\$PATH"
        line: export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
        insertafter: EOF

    - name: Install ruby 2.4.0
      command: rbenv install 2.4.0
      args:
        creates: ~/.rbenv/versions/2.4.0
    
    - name: Make ruby 2.4.0 global
      command: rbenv global 2.4.0
    
    - name: Install Bundler
      shell: eval "$(/usr/bin/rbenv init -)" && gem install bundler
      args:
        executable: /bin/bash
        creates: ~/.rbenv/versions/2.4.0/bin/bundler
    
    - name: Rehash rbenv
      command: rbenv rehash
  