---

- name: Upgrade packages
  hosts: all
  become: yes

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

- name: Create users
  hosts: all
  become: yes

  tasks:
    - name: Create user deploy
      user:
        name: deploy
        shell: /bin/bash
        groups: sudo

- name: Install rbenv and dependencies
  hosts: all
  become: yes

  tasks:
    - name: Install rbenv
      apt:
        name: rbenv
        state: present
        update_cache: yes
    
    - name: Install dependencies
      apt: 
        name: "{{ item }}" 
        state: present 
        update_cache: yes
      with_items:
        - build-essential
        - libssl-dev
        - libreadline-dev

- name: Configure rbenv
  hosts: all
  become: yes
  become_user: deploy

  tasks:
    - name: Automaticaly init rbenv
      lineinfile:
        dest: ~/.bashrc
        regexp: eval "\$\(rbenv init -\)"
        line: eval "$(rbenv init -)"
        insertafter: EOF
  